#include <Adafruit_NeoPixel.h> //Including the NeoPixel module
#define PIN 10 // This indicates the digital pin to which the WS2812 LEDs(Neo Pixels) are connected
#define NUMPIXELS 60 // The number of connected WS2812 LEDs or NeoPixels is specified here

Adafruit_NeoPixel strip = Adafruit_NeoPixel(NUMPIXELS, PIN, NEO_GRB + NEO_KHZ800); //Puts the important information in the variable strip
int pause=30000; // 30000 milliseconds pause
int buttonState = 0; //Set the button state to 0(Down)
const int ButtonPin = 5; //Indicates the digital pin to which the button is connected

// Setup
void setup() 
{
  // Initialisation of the NeoPixel
  strip.begin(); 
  strip.clear();
  strip.show();
}

// Main
void loop()
{
  buttonState = digitalRead(ButtonPin);
  if (buttonState == HIGH) 
  { 
    // When the button is pressed
    strip.setPixelColor(0, strip.Color(0,255,0)); 
    strip.show(); 
    delay (pause);
    delay (pause);
    strip.setPixelColor(1, strip.Color(0,0,255)); 
    strip.show();
    delay (pause); 
    delay (pause);
    strip.setPixelColor(2, strip.Color(200,22,0)); 
    strip.show(); 
    delay (pause);
    delay (pause);
    strip.setPixelColor(3, strip.Color(70,255,222));
    strip.show(); 
    delay (pause);
    delay (pause);
    strip.setPixelColor(4, strip.Color(0,255,0)); 
    strip.show(); 
    delay (pause); 
    delay (pause);
    strip.setPixelColor(5, strip.Color(0,0,255)); 
    strip.show();
    delay (pause);
    delay (pause); 
    strip.setPixelColor(6, strip.Color(200,22,0)); 
    strip.show(); 
    delay (pause);
    delay (pause);
    strip.setPixelColor(7, strip.Color(70,255,222));
    strip.show(); 
    delay (pause); 
    delay (pause);
    strip.setPixelColor(8, strip.Color(0,255,0)); 
    strip.show(); 
    delay (pause); 
    delay (pause);
    strip.setPixelColor(9, strip.Color(0,0,255)); 
    strip.show();
    delay (pause);
    delay (pause); 
    strip.setPixelColor(10, strip.Color(200,22,0)); 
    strip.show(); 
    delay (pause);
    delay (pause);
    strip.setPixelColor(11, strip.Color(70,255,222));
    strip.show(); 
    delay (pause);
    delay (pause);
    strip.setPixelColor(12, strip.Color(0,255,0)); 
    strip.show(); 
    delay (pause); 
    delay (pause);
    strip.setPixelColor(13, strip.Color(0,0,255)); 
    strip.show();
    delay (pause); 
    delay (pause);
    strip.setPixelColor(14, strip.Color(200,22,0)); 
    strip.show(); 
    delay (pause);
    delay (pause);
    strip.setPixelColor(15, strip.Color(0,255,0)); 
    strip.show(); 
    delay (pause);
    delay (pause);
    strip.setPixelColor(16, strip.Color(0,0,255)); 
    strip.show();
    delay (pause); 
    delay (pause);
    strip.setPixelColor(17, strip.Color(200,22,0)); 
    strip.show(); 
    delay (pause);
    delay (pause);
    strip.setPixelColor(18, strip.Color(70,255,222));
    strip.show(); 
    delay (pause);
    delay (pause);
    strip.setPixelColor(19, strip.Color(0,255,0)); 
    strip.show(); 
    delay (pause); 
    delay (pause);
    strip.setPixelColor(20, strip.Color(0,0,255)); 
    strip.show();
    delay (pause);
    delay (pause); 
    strip.setPixelColor(21, strip.Color(200,22,0)); 
    strip.show(); 
    delay (pause);
    delay (pause);
    strip.setPixelColor(22, strip.Color(70,255,222));
    strip.show(); 
    delay (pause); 
    delay (pause);
    strip.setPixelColor(23, strip.Color(0,255,0)); 
    strip.show(); 
    delay (pause); 
    delay (pause);
    strip.setPixelColor(24, strip.Color(0,0,255)); 
    strip.show();
    delay (pause);
    delay (pause); 
    strip.setPixelColor(25, strip.Color(200,22,0)); 
    strip.show(); 
    delay (pause);
    delay (pause);
    strip.setPixelColor(26, strip.Color(70,255,222));
    strip.show(); 
    delay (pause);
    delay (pause);
    strip.setPixelColor(27, strip.Color(0,255,0)); 
    strip.show(); 
    delay (pause); 
    delay (pause);
    strip.setPixelColor(28, strip.Color(0,0,255)); 
    strip.show();
    delay (pause); 
    delay (pause);
    strip.setPixelColor(29, strip.Color(200,22,0)); 
    strip.show(); 
    delay (pause);
    delay (pause);
    strip.setPixelColor(30, strip.Color(0,255,0)); 
    strip.show(); 
    delay (pause);
    delay (pause);
    strip.setPixelColor(31, strip.Color(0,0,255)); 
    strip.show();
    delay (pause); 
    delay (pause);
    strip.setPixelColor(32, strip.Color(200,22,0)); 
    strip.show(); 
    delay (pause);
    delay (pause);
    strip.setPixelColor(33, strip.Color(70,255,222));
    strip.show(); 
    delay (pause);
    delay (pause);
    strip.setPixelColor(34, strip.Color(0,255,0)); 
    strip.show(); 
    delay (pause); 
    delay (pause);
    strip.setPixelColor(35, strip.Color(0,0,255)); 
    strip.show();
    delay (pause);
    delay (pause); 
    strip.setPixelColor(36, strip.Color(200,22,0)); 
    strip.show(); 
    delay (pause);
    delay (pause);
    strip.setPixelColor(37, strip.Color(70,255,222));
    strip.show(); 
    delay (pause); 
    delay (pause);
    strip.setPixelColor(38, strip.Color(0,255,0)); 
    strip.show(); 
    delay (pause); 
    delay (pause);
    strip.setPixelColor(39, strip.Color(0,0,255)); 
    strip.show();
    delay (pause);
    delay (pause); 
    strip.setPixelColor(40, strip.Color(200,22,0)); 
    strip.show(); 
    delay (pause);
    delay (pause);
    strip.setPixelColor(41, strip.Color(70,255,222));
    strip.show(); 
    delay (pause);
    delay (pause);
    strip.setPixelColor(42, strip.Color(0,255,0)); 
    strip.show(); 
    delay (pause); 
    delay (pause);
    strip.setPixelColor(43, strip.Color(0,0,255)); 
    strip.show();
    delay (pause); 
    delay (pause);
    strip.setPixelColor(44, strip.Color(200,22,0)); 
    strip.show(); 
    delay (pause);
    delay (pause);
    strip.setPixelColor(45, strip.Color(0,255,0)); 
    strip.show(); 
    delay (pause);
    delay (pause);
    strip.setPixelColor(46, strip.Color(0,0,255)); 
    strip.show();
    delay (pause); 
    delay (pause);
    strip.setPixelColor(47, strip.Color(200,22,0)); 
    strip.show(); 
    delay (pause);
    delay (pause);
    strip.setPixelColor(48, strip.Color(70,255,222));
    strip.show(); 
    delay (pause);
    delay (pause);
    strip.setPixelColor(49, strip.Color(0,255,0)); 
    strip.show(); 
    delay (pause); 
    delay (pause);
    strip.setPixelColor(50, strip.Color(0,0,255)); 
    strip.show();
    delay (pause);
    delay (pause); 
    strip.setPixelColor(51, strip.Color(200,22,0)); 
    strip.show(); 
    delay (pause);
    delay (pause);
    strip.setPixelColor(52, strip.Color(70,255,222));
    strip.show(); 
    delay (pause); 
    delay (pause);
    strip.setPixelColor(53, strip.Color(0,255,0)); 
    strip.show(); 
    delay (pause); 
    delay (pause);
    strip.setPixelColor(54, strip.Color(0,0,255)); 
    strip.show();
    delay (pause);
    delay (pause); 
    strip.setPixelColor(55, strip.Color(200,22,0)); 
    strip.show(); 
    delay (pause);
    delay (pause);
    strip.setPixelColor(56, strip.Color(70,255,222));
    strip.show(); 
    delay (pause);
    delay (pause);
    strip.setPixelColor(57, strip.Color(0,255,0)); 
    strip.show(); 
    delay (pause); 
    delay (pause);
    strip.setPixelColor(58, strip.Color(0,0,255)); 
    strip.show();
    delay (pause); 
    delay (pause);
    strip.setPixelColor(59, strip.Color(200,22,0)); 
    strip.show(); 
    delay (pause);
    delay (pause);
    
    //All lights out at the end
    strip.setPixelColor(0, strip.Color(0,0,0)); 
    strip.show();  
    strip.setPixelColor(1, strip.Color(0,0,0)); 
    strip.show(); 
    strip.setPixelColor(2, strip.Color(0,0,0)); 
    strip.show(); 
    strip.setPixelColor(3, strip.Color(0,0,0));
    strip.show();
    strip.setPixelColor(4, strip.Color(0,0,0)); 
    strip.show();  
    strip.setPixelColor(5, strip.Color(0,0,0)); 
    strip.show(); 
    strip.setPixelColor(6, strip.Color(0,0,0)); 
    strip.show();  
    strip.setPixelColor(7, strip.Color(0,0,0));
    strip.show();
    strip.setPixelColor(8, strip.Color(0,0,0)); 
    strip.show(); 
    strip.setPixelColor(9, strip.Color(0,0,0)); 
    strip.show(); 
    strip.setPixelColor(10, strip.Color(0,0,0)); 
    strip.show(); 
    strip.setPixelColor(11, strip.Color(0,0,0));
    strip.show();
    strip.setPixelColor(12, strip.Color(0,0,0)); 
    strip.show(); 
    strip.setPixelColor(13, strip.Color(0,0,0)); 
    strip.show(); 
    strip.setPixelColor(14, strip.Color(0,0,0)); 
    strip.show(); 
    strip.setPixelColor(15, strip.Color(0,0,0));
    strip.show();
    strip.setPixelColor(16, strip.Color(0,0,0)); 
    strip.show(); 
    strip.setPixelColor(17, strip.Color(0,0,0)); 
    strip.show(); 
    strip.setPixelColor(18, strip.Color(0,0,0)); 
    strip.show(); 
    strip.setPixelColor(19, strip.Color(0,0,0));
    strip.show();
    strip.setPixelColor(20, strip.Color(0,0,0)); 
    strip.show(); 
    strip.setPixelColor(21, strip.Color(0,0,0)); 
    strip.show(); 
    strip.setPixelColor(22, strip.Color(0,0,0)); 
    strip.show(); 
    strip.setPixelColor(23, strip.Color(0,0,0));
    strip.show();
    strip.setPixelColor(24, strip.Color(0,0,0)); 
    strip.show(); 
    strip.setPixelColor(25, strip.Color(0,0,0)); 
    strip.show(); 
    strip.setPixelColor(26, strip.Color(0,0,0)); 
    strip.show(); 
    strip.setPixelColor(27, strip.Color(0,0,0));
    strip.show();
    strip.setPixelColor(28, strip.Color(0,0,0)); 
    strip.show(); 
    strip.setPixelColor(29, strip.Color(0,0,0)); 
    strip.show(); 
    strip.setPixelColor(30, strip.Color(0,0,0)); 
    strip.show(); 
    strip.setPixelColor(31, strip.Color(0,0,0));
    strip.show();
    strip.setPixelColor(32, strip.Color(0,0,0)); 
    strip.show(); 
    strip.setPixelColor(33, strip.Color(0,0,0)); 
    strip.show(); 
    strip.setPixelColor(34, strip.Color(0,0,0)); 
    strip.show(); 
    strip.setPixelColor(35, strip.Color(0,0,0));
    strip.show();
    strip.setPixelColor(36, strip.Color(0,0,0)); 
    strip.show(); 
    strip.setPixelColor(37, strip.Color(0,0,0)); 
    strip.show(); 
    strip.setPixelColor(38, strip.Color(0,0,0)); 
    strip.show(); 
    strip.setPixelColor(39, strip.Color(0,0,0));
    strip.show();
    strip.setPixelColor(40, strip.Color(0,0,0)); 
    strip.show(); 
    strip.setPixelColor(41, strip.Color(0,0,0)); 
    strip.show(); 
    strip.setPixelColor(42, strip.Color(0,0,0)); 
    strip.show(); 
    strip.setPixelColor(43, strip.Color(0,0,0));
    strip.show();
    strip.setPixelColor(44, strip.Color(0,0,0)); 
    strip.show(); 
    strip.setPixelColor(45, strip.Color(0,0,0)); 
    strip.show(); 
    strip.setPixelColor(46, strip.Color(0,0,0)); 
    strip.show();  
    strip.setPixelColor(47, strip.Color(0,0,0));
    strip.show();
    strip.setPixelColor(48, strip.Color(0,0,0)); 
    strip.show(); 
    strip.setPixelColor(49, strip.Color(0,0,0)); 
    strip.show();  
    strip.setPixelColor(50, strip.Color(0,0,0)); 
    strip.show(); 
    strip.setPixelColor(51, strip.Color(0,0,0));
    strip.show();
    strip.setPixelColor(52, strip.Color(0,0,0)); 
    strip.show(); 
    strip.setPixelColor(53, strip.Color(0,0,0)); 
    strip.show(); 
    strip.setPixelColor(54, strip.Color(0,0,0)); 
    strip.show(); 
    strip.setPixelColor(55, strip.Color(0,0,0));
    strip.show();
    strip.setPixelColor(56, strip.Color(0,0,0)); 
    strip.show(); 
    strip.setPixelColor(57, strip.Color(0,0,0)); 
    strip.show(); 
    strip.setPixelColor(58, strip.Color(0,0,0)); 
    strip.show(); 
    strip.setPixelColor(59, strip.Color(0,0,0));
    strip.show();
  }
}
